### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by LoweDavince** [Rhoban/RhIO#1]
Could not find a package configuration file provided by "Deps" with any of
  the following names:

    DepsConfig.cmake
    deps-config.cmake

**Comment by Gregwar** [comment]
Hello
RhIO now uses deps which is a lightweight tool to handle dependencies
To install it you can simply install deps:
https://github.com/Rhoban/deps

And type:
    deps install rhoban/rhio

We should however update the documentation ping @leph

**Comment by Gregwar** [comment]
I've updated the [Getting started](https://github.com/Rhoban/RhIO/blob/master/Docs/getting_started.md) section, which should now contains valid installation instructions

**Comment by Gregwar** [comment]
Is it OK for you?
If you need further details do not hesitate to open more issues

**Comment by LoweDavince** [comment]
Of course , it works as expected. thank you :)
