### ISSUE TITLE
view frame

### ISSUE THREAD

**Issue by LoweDavince** [Rhoban/RhIO#2]
when i run `./testImgs` and `rhio `shell command, after typing `view frame1` , it seems there is no image.
Am i wrong to miss something install just like `apt-get install gnuplot`? or it is no image can view originally . 

Thanks & regards

**Comment by Gregwar** [comment]
Hello,
Again, sorry for the misdocumentation, you should install the `ffplay` utility which is used as an external command just like gnuplot for plot
Keep the issue opened until we fix the documentation

**Comment by Gregwar** [comment]
Just curious, you participate to the Robocup? Which league?

**Comment by LoweDavince** [comment]
Yes, I participate in Humanoid kidsize league . i'm a team member from zjudancer.  :-)

**Comment by Leph** [comment]
Ok, so I added some more documentation about streams ans frames. There now also should have a more explicit error message when ffplay or gnuplot could not be found.
